apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.4.196
    path: "/mnt/nfsshare"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi